### ISSUE TITLE
Publish this as GitHub page?

### ISSUE THREAD

**Issue by devurandom** [flyingmachine/brave-clojure-web#135]
It would be nice if you could publish this as a GitHub page, so one could directly read through the corrected version to search, find and report only those errors that still exist in this version.

I know that I found lots of errors on http://braveclojure.com/, but I would assume that many are already fixed in this repository. I don't want to waste anyone's time searching for errors that don't exist anymore.

And then there is also #82, which suggests that finding the errors on braveclojure.com in this repository might be very hard.

OT-question: Do you still plan to merge all the other PRs? It'd be a waste of everyone's time, if I created a big PR with all the errors I found and then you have to merge this and sort out any overlap with all the other PRs.

**Comment by devurandom** [comment]
I figured out that building the site locally is not has hard as I thought.

**Comment by dijonkitchen** [comment]
I think this is still valid. Probably still want the book to be served via GitHub Pages so that it updates live rather than however it's done via Adobe InDesign. The HTML is hard to read!
