### ISSUE TITLE
Bad markdown processing in To Catch a Burgler

### ISSUE THREAD

**Issue by vermiculus** [flyingmachine/brave-clojure-web#80]
[See the actual page](http://www.braveclojure.com/organization/#6__To_Catch_a_Burglar) and search for `The innermost loop takes a seq of keys`. It looks fine on GitHub, so I'm hesitant to just fix with a PR :smile: Something is wrong in the site generation.

**Comment by flyingmachine** [comment]
The site's since been massively updated; hopefully this isn't an issue anymore :) Thanks for the note!

**Comment by vermiculus** [comment]
Are you telling me I've got to read it again!? :smile: Looks like the problem is gone. I'll keep my eye out for any other such issues!
